json.username user.username
json.id user.id
json.band_name user.band_name
json.bio user.bio
json.primary_color user.primary_color
json.secondary_color user.secondary_color
json.text_color user.text_color
json.artist_pic asset_path(user.artist_pic.url(:full))
json.band_header asset_path(user.band_header.url(:full))
